config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:create]
  resources :sessions, only: [:create, :destroy]
  resources :projects do
    resources :project_comments, except: :show
    resources :tools, only: :new
  end
  get "dashboard", to: 'dashboards#dashboard', as: "dashboard"
  root to: 'home#welcome'
  get "login", to: 'sessions#new', as: "login"
  get "logout", to: 'sessions#destroy', as: "logout"
  get "registration", to: "users#new", as: "registration"
  get '/auth/:provider/callback' => 'sessions#omniauth'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :teams, :dependent => :destroy
    has_many :project_tools, :dependent => :destroy
    has_many :users, through: :teams, :dependent => :destroy
    has_many :tools, through: :project_tools, :dependent => :destroy
    has_many :project_comments, :dependent => :destroy

    accepts_nested_attributes_for :users, :tools, :project_comments, reject_if: :all_blank

    validates :name, presence: true, uniqueness: true
    validates :location, presence: true, uniqueness: true

    scope :active, -> { where("? BETWEEN start_date AND end_date", Date.today)} 
    scope :past, -> { where('end_date < ?', Date.today)} 
    scope :future, -> { where('start_date > ?', Date.today)} 
end

app/models/project_comment.rb
class ProjectComment < ApplicationRecord
  belongs_to :project

  validates :title, presence: true
  validates :body, presence: true
end

app/models/project_tool.rb
class ProjectTool < ApplicationRecord
    belongs_to :tool
    belongs_to :project
end

app/models/team.rb
class Team < ApplicationRecord
    belongs_to :user
    belongs_to :project
end

app/models/tool.rb
class Tool < ApplicationRecord
    has_many :project_tools, :dependent => :destroy
    has_many :projects, through: :project_tools, :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    enum role: [:employee, :admin]
    has_many :teams, :dependent => :destroy
    has_many :projects, through: :teams, :dependent => :destroy

    validates :email, presence: true, uniqueness: true

    def self.from_omniauth(response)
        User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u|
            u.name = response[:info][:name]
            u.email = response[:info][:email]
            u.password = SecureRandom.hex(15)
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    private

    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        else
            @current_user = nil
        end
    end

    def authenticate_admin!
        if !current_user.admin?
            flash[:alert] = "You do not have access to this page. Admin Only."
            redirect_to dashboard_path
        end
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    before_action :require_login

    def dashboard
        if current_user.admin?
            @projects = Project.all
            @active_projects = Project.active
            @future_projects = Project.future
            @past_projects = Project.past
            @tools = Tool.all
        else
            @projects = current_user.projects
        end
    end

  private

    def require_login
        unless current_user
        flash[:alert] = "You must be logged in to access this section."
        redirect_to login_path
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def welcome
    end
end

app/controllers/project_comments_controller.rb
class ProjectCommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]

    def index
      @project= Project.find(params[:project_id])
    end
    def new
      @comment = ProjectComment.new
    end
  
    def create
      @comment = ProjectComment.new(project_comment_params)
      @comment.project_id = params[:project_id]
      if @comment.save
        flash[:notice] = "Your comment has been created."
        redirect_to project_project_comments_path(params[:project_id])
      else
        render :new
      end
    end
  
    def edit
    end

    def update
      if @comment.update(project_comment_params)
        flash[:notice]= "Comment updated"
        redirect_to dashboard_path
      else
        flash[:alert]= "Comment update was unsuccessful."
        render :edit
      end    
      #comment = ProjectComment.new(project_comment_params) 
    end

    def destroy
      @comment.delete
      reload
    end

    private

    def set_comment
      @comment = ProjectComment.find(params[:id])
    end

    def project_comment_params
      params.required(:project_comment).permit(
      :title,
      :body
    )
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_admin!, except: :show
  before_action :set_project, except: [:new, :create]

  def new
    @project = Project.new
    5.times {@project.tools.build}
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Your project has been created."
      redirect_to dashboard_path
    else 
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:notice]= "Project updated"
      redirect_to dashboard_path
    else
      flash[:alert]= "Project update was unsuccessful."
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to dashboard_path, notice: "Successful Project Deletion."
  end

  def show
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.required(:project).permit(
      :name,
      :location,
      :start_date,
      :end_date,
      :description,
      :revenue_estimate, 
      :cost_estimate,
      user_ids: [],
      tools_attributes: [:item_name, :description, :quantity],
      project_comments_attributes: [:title, :body]
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_path, notice: "You are logged in!"
    else
      if user == nil
        flash[:alert] = "Invalid email.  Please try again."
      else
        flash[:alert] = "Invalid password."
      end
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: "Successful logout.  Please login to come back."
  end

  def omniauth
    user = User.from_omniauth(request.env['omniauth.auth'])
    if user.valid?
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      redirect to '/login'
    end
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path, notice: "Welcome! This is your dashboard, take a look around..."
    else 
      render :new
    end
  end

  private

  def user_params
    params.required(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_message
        if flash[:notice] || flash[:alert] 
            content_tag(:div, flash[:notice] || flash[:alert], class: "alert alert-#{flash[:notice] ? 'success' : 'danger'} alert dismissable fade show m-0", role:'alert')
        end   
    end
end

app/views/dashboards/_admin_dash.html.erb
<%= link_to "Add a new project", new_project_path, class: "btn btn-primary" %>
<div class="container">
    <div class="row">
        <div class="col-md-3 col-sm-6">
            <h2>All Projects:</h2>
            <% @projects.each do |project| %>
                <div class="my-3">
                    <%= link_to project.name, project_path(project), class: "btn btn-secondary" %>
                </div>
            <% end %>
        </div>
        <div class="col-md-3 col-sm-6">
            <h2>Current/Active Projects:</h2>
            <% @active_projects.each do |project| %>
                <div class="my-3">
                    <%= link_to project.name, project_path(project), class: "btn btn-secondary" %>
                </div>
            <% end %>
        </div>
        <div class="col-md-3 col-sm-6">
            <h2>Past Projects:</h2>
            <% if @past_projects.any? %>
            <% @past_projects.each do |project| %>
                <div class="my-3">
                    <%= link_to project.name, project_path(project), class: "btn btn-secondary" %>
                </div>
            <% end %>
        <% else %>
            <h3>No past projects, yet.</h3>
        <% end %>
        </div>
        <div class="col-md-3 col-sm-6">
            <h2>Future Projects:</h2>
            <% if @future_projects.any? %>
                <% @future_projects.each do |project| %>
                    <div class="my-3">
                        <%= link_to project.name, project_path(project), class: "btn btn-secondary" %>
                    </div>
                <% end %>
            <% else %>
                <h3>No future projects, yet.</h3>
            <% end %>
        </div>
    </div>
</div>

app/views/dashboards/_employee_dash.html.erb
<div>
    <h2>Your current projects:</h2>
    <% if @projects.any? %>
        <% @projects.each do |project| %>
            <%= link_to project.name, project_path(project), class: "my-3" %>
        <% end %>
    <% else %>
        <h3>No projects, yet.</h3>
    <% end %>
      
</div>

app/views/dashboards/dashboard.html.erb
<h1>Hi, <%= current_user.name %> </h1>
<h2>This is your dashboard.  Explore...</h2>
<% if current_user.admin? %>
    <%= render 'admin_dash' %>
<% else %>
    <%= render 'employee_dash' %>
<% end %>

app/views/home/welcome.html.erb
<div class="container">
  <div class="row">
  <div class="col"></div>
  <div class="col"></div>
        <div class="col-sm">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                <h5 class="card-title">Welcome to our website.</h5>
                <p class="card-text">New users must register for their account. Existing users, login here.</p>
                <%#= link_to ... %>
                <a href="/registration" class="btn btn-outline-primary">Register</a>
                <%#= link_to ... %>
                <a href="/login" class="btn btn-primary">Login</a>
                </div>
            </div>
        </div>
    </div> 
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous" />
    <title>Paragon Painting & Waterproofing</title>
  </head>
  <body>
    <%= flash_message %>
    <% if current_user %>
      <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <%= link_to "Paragon Painting & Waterproofing", dashboard_path, class: "btn btn-primary" %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <%= link_to "Dashboard", dashboard_path, class: "btn btn-primary" %>     
                </li>
                <li class="nav-item">
                  <%= link_to "Logout", logout_path, class: "btn btn-primary" %>
                </li>
              </ul>
            </div>
        </nav>
      </header>
    <% else %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
    <%= link_to "Paragon Painting & Waterproofing", root_path, class: "btn btn-primary" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "btn btn-primary" %>
        </li>
        <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <% end %>
    
    <div class="wrapper">

        <%= yield %>

      <footer class="branding">
        <small>&copy; 2021 <strong>Paragon Painting & Waterproofing</strong></small>
      </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <!--[if lt IE 7]>
      <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
      <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
    <![endif]-->
  </body>
</html>

app/views/project_comments/_form.html.erb
<% if @comment.errors.any? %>
    <div> There are errors. </div> 
    <ul>
        <% @comment.errors.full_messages.each do |message|%>
            <li> <%= message %> </li>
        <% end %>
    </ul>
<% end %>
<%= form_with model: [:project, @comment] do |f| %>
    <%= f.label "Title:" %>
    <%= f.text_field :title %><br/>
    <%= f.label "Body:" %>
    <%= f.text_area :body %><br>
    <% if params[:action] == 'new' %>  
        <%= f.submit "Create Comment!", class: "btn btn-success my-3" %>
    <% else %>
        <%= f.submit "Update", class: "btn btn-success my-3" %>
    <% end %>
<% end %>

app/views/project_comments/edit.html.erb
<h1>Edit Comment:</h1>
<%= render 'form' %>

app/views/project_comments/index.html.erb
<h1 class="text-center"><%= @project.name %> Project Comments:</h1>
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-6 mx-auto p-3 border border-dark">
            <section class="my-3">
            <% if @project.project_comments.any? %>
                <% @project.project_comments.each do |comment|%>
                    <h3><%= comment.title %></h3>
                    <p><%= comment.body %></p>
                <% end %>
            <% else %>
                <p>No comments, yet.</p>
            <% end %>
            </section>
            <%= link_to "Add A Comment", new_project_project_comment_path, class: "btn btn-primary btn-lg" %>
        </div>
    </div>
</div>

app/views/project_comments/new.html.erb
<h1>Add Comment:</h1>
<%= render 'form' %>

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
    <div> There are errors. </div> 
    <ul>
        <% @project.errors.full_messages.each do |message|%>
            <li> <%= message %> </li>
        <% end %>
    </ul>
<% end %>
<%= form_with(model: @project) do |f| %>
    <%= f.label "Name:" %>
    <%= f.text_field :name %><br/>
    <%= f.label "Location:" %>
    <%= f.text_field :location %><br/>
    <%= f.label "Description:" %>
    <%= f.text_field :description %><br/>
    <%= f.label "Start Date:" %>
    <%= f.date_field :start_date %><br/>
    <%= f.label "End Date:" %>
    <%= f.date_field :end_date %><br/>
    <%= f.label "Revenue Estimate:" %>
    <%= f.number_field :revenue_estimate, step: 0.01, min: 0 %><br/>
    <%= f.label "Cost Estimate:" %>
    <%= f.number_field :cost_estimate, step: 0.01, min: 0 %><br/>
    <h3 class="mt-3">Users:</h3>
    <%= f.collection_check_boxes(:user_ids, User.order(:name), :id, :name) do |user| %>
        <div>
        <%= user.label class:"label-checkbox" do %>
            <%= user.check_box + user.text%>
        <% end %>
        </div>
    <%end%>
    <h3 class="mt-3">Tools:</h3>
    <ul>
        <%= f.fields_for :tools do |tools_form| %>
        <li>
            <%= tools_form.label "Tool Name:" %>
            <%= tools_form.text_field :item_name %>
        </li>
        <li>
            <%= tools_form.label :description %>
            <%= tools_form.text_field :description %>
        </li>
            <%= tools_form.label :quantity %>
            <%= tools_form.number_field :quantity, min: 0, step: 1 %>
        </li>
        <hr>
        <% end %>
    </ul>
    <% if params[:action] == 'new' %>  
        <%= f.submit "Create Project!", class: "btn btn-success my-3" %>
    <% else %>
        <%= f.submit "Update", class: "btn btn-success my-3" %>
    <% end %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit the project: <%= @project.name %></h1>
<%= render 'form' %>

app/views/projects/new.html.erb
<h1>Add a new project:</h1>
<%= render 'form' %>

app/views/projects/show.html.erb
<h1 class="text-center"><%= @project.name %></h1>
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-4">
            <h2 class="text center">Project Details</h2>
            <ul>
                <li>Location: <%= @project.location %></li>
                <li>Start Date: <%= @project.start_date %></li>
                <li>End Date: <%= @project.end_date %></li>
                <li>Description: <%= @project.description %></li>
                <% if current_user.admin? %>
                    <li>Revenue Estimate: $<%= @project.revenue_estimate %></li>
                    <li>Cost Estimate: $<%= @project.cost_estimate %></li>
                <% end %>
            </ul>
        </div>
        <div class="col-sm-12 col-md-4">
            <h2 class="text-center">Team Members</h2>
            <% @project.users.each do |employee| %>
                <li><%= employee.name %></li>
            <% end %>
        </div>
        <div class="col-sm-12 col-md-4">
            <h2 class="text-center">Tools</h2>
            <% @project.tools.each do |tool| %>
                <li><%= tool.item_name %></li>
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <%= link_to "See Comment Thread", project_project_comments_path(@project), class: "btn btn-success" %>
        </div>        
    </div>
</div>

<% if current_user.admin? %>
    <div class="row flex-column align-items-center bg-light p-4">
        <%= link_to "Edit", edit_project_path(@project), class: "btn btn-warning btn-lg w-auto" %>
        <div class="border border-danger p-4 my-3 w-auto text-center">
            <h3>Danger Zone: Action Can't Be Undone!</h3>
            <%= button_to "Delete", project_path(@project), method: :delete, class: "btn btn-danger btn-lg", data: { Confirm: 'Are you sure?' } %>
        </div>
    </div>
<% end %>

app/views/tools/new.html.erb
<h1>Tools#new</h1>
<p>Find me in app/views/tools/new.html.erb</p>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
  <div class="col"></div>
  <div class="col"></div>
        <div class="col-sm">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                <h5 class="card-title">Welcome to our website.</h5>
                <p class="card-text">New users must register for their account. Existing users, login here.</p>
                <a href="/registration" class="btn btn-outline-primary">Register</a>
                <a href="/login" class="btn btn-primary">Login</a>
                </div>
            </div>
        </div>
    </div> 
</div>

app/views/users/new.html.erb
<h1>New member? Register here.</h1>
<% if @user.errors.any? %>
    <div> There are errors. </div> 
    <ul>
    <% @user.errors.full_messages.each do |message|%>
        <li> <%= message %> </li>
    <% end %>

    </ul>
<% end %>

<%= form_with model: @user, url: "/users" do |f| %>
    <%= f.label "Name:" %>
    <%= f.text_field :name %><br/>
    <%= f.label "E-Mail:" %>
    <%= f.email_field :email %><br/>
    <%= f.label "Password:" %>
    <%= f.password_field :password %><br/> 
    <%= f.submit "Join Paragon today!" %>
<% end %>
<%= button_to "Log in with Google", '/auth/google_oauth2'  %>